---
title: "sas_two sample test analysis"
author: "Maria Ambrosio"
date: '2022-09-05'
output: html_document
---

libname pg1 "/home/u45033532/EPG1V2/data";
run;

libname heart1 "/home/u45033532/MyExercises/Heart1";
run;

/* Get an overview of data */
proc contents data=sashelp.heart;
run;

/* Create temporary table Heart1 (include only participants with age group between 20 and 50y alive) */
proc sort data=sashelp.heart out=heart1;
by AgeAtStart descending Cholesterol;
/* Delete columns where Status is dead and Smoking Status is missing */
where Status ne "Dead" and Smoking_Status not is null 
and Weight_Status not is null;
by descending _ALL_;
run;

/* Grouping smoking status */
data smoking_status_grouped;
set heart1;
output;
Smoking_Status= "All";
run;

/* order to smoking status */
data ordered_smoking_status_grouped;
set smoking_status_grouped;
/* Smoking status assigned acronym */
if INDEX (Smoking_Status, "Non-smoker")>0 then do; SS="A";ORD=1;END;
if INDEX (Smoking_Status, "Light (1-5)")>0 then do; SS="B";ORD=2;End;
if INDEX (Smoking_Status, "Moderate (6-15)")>0 then do; SS="C";ORD=3;END;
if INDEX (Smoking_Status, "Heavy (16-25)")>0 then do; SS="D";ORD=4;END;
if INDEX (Smoking_Status, "Very Heavy (> 25)")>0 then do; SS="E";ORD=5;END;
keep SS Smoking_Status ORD Weight Weight_Status AgeAtStart Sex Cholesterol BP_Status Chol_Status Diastolic Systolic;
run;

proc sort ;by SS ORD; run;

/* Estimating the mean age to start smoking */
title Estimates of mean smoking start age of Light (1-5) smokers;
proc means data=ordered_smoking_status_grouped  mean median max min std;
var AgeAtStart;
where SS="B";
run;

title Estimates of mean smoking start age of Moderate (6-15) smokers;
proc means data=ordered_smoking_status_grouped  mean median max min std;
var AgeAtStart;
where SS="C";
run;

title Estimates of mean smoking start age of Heavy (16-25) smokers;
proc means data=ordered_smoking_status_grouped  mean median max min std;
var AgeAtStart;
where SS="D";
run;

title Estimates of mean smoking start age of Very Heavy (>25) smokers;
proc means data=ordered_smoking_status_grouped  mean median max min std;
var AgeAtStart;
where SS="E";
run;

title Estimates of mean smoking start age by sex;
proc means data=ordered_smoking_status_grouped  mean median max min std;
var AgeAtStart;
where Sex= "Female";
run;

proc means data=ordered_smoking_status_grouped  mean median max min std;
var AgeAtStart;
where Sex= "Male";
run;


/* 2-sample hypothesis test */
/* Format set to binomial values */
proc format;
value $Sexfmt 'Female'='1' 'Male'='0';
value $Smoking_Statusfmt 'Light (1-5)'='1' 'Moderate (6-15)'='2' 'Heavy (16-25)'='3' 'Very Heavy (> 25)'='4'; 
value AgeAtStartfmt 20 - 29= "1"
                    30 - 39=  "2"
                    40 - 50=   "3"
                    51 - high= "4";
run;      

/* Avaliar as idades que cada smoking category comecou a fumar */
ods graphics on;
title1 "Age of Start Smoking Proportions Across Smoking Groups";
title2 "Light, Moderate and Heavy Smokers";
proc freq data=heart1 order= internal;
format Smoking_Status $Smoking_Statusfmt. AgeAtStart AgeAtStartfmt. Sex $Sexfmt.;
/* Weight AgeAtStart; */
tables Smoking_Status*AgeAtStart/nocum plots=freqplot(group=row scale=grouppercent orient=horizontal) ;
/* plots=freqplot(twoway=stacked orient=horizonta); */
where Smoking_Status ne "Non-smoker";
run;

/* Mean comparison */
data smoking_dataanalysis;
input Smoking_Status MeanAgeAtStart;
lable MeanAgeAtStart="Mean Age of Smoking Start";
datalines; 
1 

/* Print table to see if formats were created  */
/* proc print data=heart1; */
/* format  Smoking_Status $Smoking_Statusfmt. AgeAtStart AgeAtStartfmt. Sex $Sexfmt.; */
/* run; */
 

/* H0=Age to start smoking/ There is no difference on ageatstart proportions accross smoking groups */

data smoking_dataanalysis;
input Smoking_Status AgeAtStart N;
Label AgeAtStart="Age of Smoking Start";  
/* format Smoking_Status $Smoking_Statusfmt. AgeAtStart AgeAtStartfmt. Sex $Sexfmt.; */
datalines;
1 1 2 
1 2 197
1 3 137
1 4 55
2 1 3
2 2 213
2 3 113
2 4 33
3 1 7
3 2 358
3 3 190 
3 4 48 
;
run;

/* Create permanent table  */
libname out "/home/u45033532/MyExercises/Heart1/output";
run;
data smoking_light_moderate; 
set smoking_dataanalysis;
/* by descending _ALL_; */
run;

/* Print table created  */
/* proc print data= smoking_light_moderate label noobs; */
/* label Smoking_Status= 'Smoking Status Group' AgeAtStart= 'Smoking Start Age'; */
/* run; */

/* Vizualize count of AgeAtStart across smoking groups  based on the datalines created */
ods graphics on;
ods noproctitle;
title Age of Start Smoking Proportions Across Smoking Groups;
proc freq data = smoking_light_moderate order=internal;
weight N;
tables Smoking_Status*AgeAtStart/nocum plots=freqplot(group=row scale=grouppercent orient=horizontal);
run;
title;



/* Conduct one sample t-test to estimate the compare smoking status mean age of start smoking  */




proc ttest data=smoking_dataanalysis H0=0 Sides=2;
Weight N;
class Smoking_Status;
Var AgeAtStart;
run;





proc freq data=smoking_light_moderate order=freq;
Weight N;
tables Smoking_Status*AgeAtStart/relrisk;
run;

proc freq data=smoking_dataanalysis;
Weight N;
tables Smoking_status*AgeAtStart/Chisq;
run;

proc univariate data=smoking_dataanalysis;
Weight N;
var Smoking_Status;
run;

proc ttest data=smoking_dataanalysis H0=0 Sides=2;
Weight N;
class Smoking_Status;
Var AgeAtStart;
run;









